
pd1=Pipeline.constructTestPlotData('max_cores',6,...
    'normVar',1 ...
    );

pd2=Pipeline.constructTestPlotData('max_cores',6,...
    'CRecurX',0,'CRecurY',0,'CRecurZ',0,...
    'normVar',1 ...
    );

exit
