
pd1=Pipeline.constructTestPlotData('max_cores',12,...
    'CRecurY',0.6,...
    'preSource',false ...
    );

pd2=Pipeline.constructTestPlotData('max_cores',12,...
    'CRecurY',0.4,...
    'preSource',false ...
    );

exit
