
%

h   = s20150605_plot_thresholds(...
        'fakedata'  , false     , ...
        'nogen'     , false     , ...
        'noplot'    , true      , ...
        'max_cores' , 6           ...
        );

exit
