
pd1=Pipeline.constructTestPlotData('max_cores',12,...
    'preSource',false ...
    );

pd2=Pipeline.constructTestPlotData('max_cores',12,...
    'normVar',1,...
    'preSource',false ...
    );

pd3=Pipeline.constructTestPlotData('max_cores',12,...
    'CRecurX',0,'CRecurY',0,'CRecurZ',0,...
    'preSource',false ...
    );

pd4=Pipeline.constructTestPlotData('max_cores',12,...
    'CRecurX',0,'CRecurY',0,'CRecurZ',0,...
    'normVar',1,...
    'preSource',false ...
    );

exit
