
pd1=Pipeline.constructTestPlotData('max_cores',12,...
    'CRecurY',0.5,...
    'preSource',false ...
    );

pd2=Pipeline.constructTestPlotData('max_cores',12,...
    'CRecurY',0.35,...
    'preSource',false ...
    );

exit
