
set_iflow_path

pd1=Pipeline.constructTestPlotData('max_cores',6,...
    'WSquash',true,'WSumTweak',true...
    );

pd2=Pipeline.constructTestPlotData('max_cores',6,...
    'CRecurX',0,'CRecurY',0,'CRecurZ',0,...
    'WSquash',true,'WSumTweak',true...
    );

exit
