function h = Plot(obj,varargin)
% subject.assess.base.Plot
% 
% Description:	plot the results of the assessment
% 
% Syntax: h = obj.Plot([kTask]=1,<options>)
% 
% In:
%	[kTask]	- the index of the task for which to plot results
%	<options>:
%		performance:	(true) true to plot the subject performance
%		ability:		(true) true to plot the ability estimate as a function
%						of probe number
%		slope:			(true) true to plot the steepness estimate as a function
%						of probe number
%		rmse:			(true) true to plot the rmse as a function of probe
%						number
%		r2:				(true) true to plot the r^2 as a function of probe
%						number
% 
% Out:
%	h	- a struct of plot handles
% 
% Updated:	2015-12-04
% Copyright 2015 Alex Schlegel (schlegel@gmail.com). This work is licensed
% under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported
% License.

%parse the inputs
	[kTask,opt]	= ParseArgs(varargin,1,...
					'performance'	, true	, ...
					'ability'		, true	, ...
					'slope'			, true	, ...
					'rmse'			, true	, ...
					'r2'			, true	  ...
					);

h	= struct;

if opt.performance
	sPerformance	= obj.GetTaskPerformance(kTask);
	sEstimate		= obj.GetTaskEstimate(kTask);
	
	d	= sPerformance.d;
	f	= 100*sPerformance.f;
	n	= sPerformance.n;
	
	fEstimate	= 100*weibull(1-d,1-sEstimate.ability,sEstimate.slope,0,sEstimate.chance,sEstimate.target,sEstimate.lapse);
	
	nSample	= numel(d);
	
	col		= GetPlotColors(2);
	col		= [repmat(col(1,:),[nSample 1]); col(2,:)];
	
	dSep	= num2cell(d);
	fSep	= num2cell(f);
	
	cLineStyle	= [repmat({'none'},[nSample 1]); '-'];
	cMarker		= [repmat({'.'},[nSample 1]); 'none'];
	markerSize	= [MapValue(n,0,max(n),10,80); 0];
	
	h.performance	= alexplot([dSep; d],[fSep; fEstimate],...
						'title'			, 'performance'	, ...
						'xlabel'		, 'd'			, ...
						'ylabel'		, '% correct'	, ...
						'xmin'			, 0				, ...
						'xmax'			, 1				, ...
						'ymin'			, 0				, ...
						'ymax'			, 100			, ...
						'color'			, col			, ...
						'linestyle'		, cLineStyle	, ...
						'marker'		, cMarker		, ...
						'markersize'	, 20			, ...
						'type'			, 'line'		  ...
						);
	
	for kS=1:nSample
		set(h.performance.hP(kS),'MarkerSize',markerSize(kS));
	end
end

if opt.ability || opt.slope || opt.rmse || opt.r2
	sHistory	= obj.GetTaskHistory(kTask);
	
	hMulti	= {};
	
	nPlot	= opt.ability + opt.slope + opt.rmse + opt.r2;
	hFigure	= switch2(nPlot,1,[],2,300,3,250,4,200);
	
	nProbe	= numel(sHistory.d);
	kProbe	= (1:nProbe)';
	
	if opt.ability
		h.ability	= alexplot(kProbe,sHistory.ability,...
						'title'			, 'psychometric fit'	, ...
						'xlabel'		, 'probe'				, ...
						'ylabel'		, 'ability estimate'	, ...
						'ymin'			, 0						, ...
						'ymax'			, 1						, ...
						'linewidth'		, 1						, ...
						'h'				, hFigure				, ...
						'type'			, 'line'				  ...
						);
		
		hMulti{end+1}	= h.ability;
	end
	
	if opt.slope
		h.slope	= alexplot(kProbe,sHistory.slope,...
						'xlabel'		, 'probe'	, ...
						'ylabel'		, 'slope'	, ...
						'linewidth'		, 1			, ...
						'h'				, hFigure	, ...
						'type'			, 'line'	  ...
						);
		
		hMulti{end+1}	= h.slope;
	end
	
	if opt.rmse
		h.rmse	= alexplot(kProbe,sHistory.rmse,...
					'xlabel'		, 'probe'	, ...
					'ylabel'		, 'RMSE'	, ...
					'ymin'			, 0			, ...
					'ymax'			, 1			, ...
					'linewidth'		, 1			, ...
					'h'				, hFigure	, ...
					'type'			, 'line'	  ...
					);
		
		hMulti{end+1}	= h.rmse;
	end
	
	if opt.r2
		h.r2	= alexplot(kProbe,sHistory.r2,...
					'xlabel'		, 'probe'	, ...
					'ylabel'		, 'r^2'		, ...
					'ymin'			, 0			, ...
					'ymax'			, 1			, ...
					'linewidth'		, 1			, ...
					'h'				, hFigure	, ...
					'type'			, 'line'	  ...
					);
		
		hMulti{end+1}	= h.r2;
	end
	
	if numel(hMulti)>1
		h.combined	= multiplot(reshape(hMulti,[],1),...
						'label'		, false	, ...
						'spacer'	, false	  ...
						);
	end
end
