function s = p_GetTouch(wac)
% p_GetTouch
% 
% Description:	get the current state of the touch
% 
% Syntax:	s = p_GetTouch(wac)
% 
% Updated: 2012-11-26
% Copyright 2012 Alex Schlegel (schlegel@gmail.com).  This work is licensed
% under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported
% License.
[x,y,but,focus,v,vInfo]	= GetMouse([],wac.deviceid(3));

s	= struct(...
		'x'			, (v(1)-vInfo(1).min)./(vInfo(1).max-vInfo(1).min)	, ...
		'y'			, (v(2)-vInfo(2).min)./(vInfo(2).max-vInfo(2).min)	, ...
		'button'	, 0													, ...
		'p'			, NaN												, ...
		'tx'		, NaN												, ...
		'ty'		, NaN												  ...
		);
