function s = p_GetStylus(wac)
% p_GetStylus
% 
% Description:	get the current state of the stylus
% 
% Syntax:	s = p_GetStylus(wac)
% 
% Updated: 2012-11-26
% Copyright 2012 Alex Schlegel (schlegel@gmail.com).  This work is licensed
% under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported
% License.
[x,y,but,focus,v,vInfo]	= GetMouse([],wac.deviceid(1));

s	= struct(...
		'x'			, (v(1)-vInfo(1).min)./(vInfo(1).max-vInfo(1).min)			, ...
		'y'			, (v(2)-vInfo(2).min)./(vInfo(2).max-vInfo(2).min)			, ...
		'button'	, but(1)													, ...
		'p'			, (v(3)-vInfo(3).min)./(vInfo(3).max-vInfo(3).min)			, ...
		'tx'		, -1 + 2*(v(4)-vInfo(4).min)./(vInfo(4).max-vInfo(4).min)	, ...
		'ty'		, -1 + 2*(v(5)-vInfo(5).min)./(vInfo(5).max-vInfo(5).min)	  ...
		);
