% Copyright (c) 2014 Trustees of Dartmouth College. All rights reserved.

classdef Opts
	% Opts:  Options for causal simulator
	%   TODO: Add detailed comments

	properties
	end

	methods (Static)
		function optcell = getDefaultBaseParams
			optcell = {...
				'sourceNoisiness'	, 1.0e-6	, ...
				'destNoisiness'		, 1.0e-6	, ...
				'numTimeSteps'		, 1000		, ...
				'numFuncSigs'		, 10		, ...
				'numVoxelSigs'		, 500		, ...
				'numTopComponents'	, 10		  ...
			};
		end
		function optcell = getDefaultSimParams
			optcell = {...
				'isDestBalancing'	, false		, ...
				'iterations'		, 1			, ...
				'maxWOnes'			, 4			, ...
				'outlierPercentage'	, 5			, ...
				... %'pcaPolicy'			, 'default'	, ...
				'pcaPolicy'			, 'skip'	, ...
				'recurStrength'		, 0.8		, ...
				'rngSeedBase'		, 0			, ...
				'voxelFreedom'		, 1.000		  ...
			};
		end
		function [opt,optcell] = getOptDefaults
			baseParams = Opts.getDefaultBaseParams;
			simParams = Opts.getDefaultSimParams;

			optcell = {baseParams{:} simParams{:}};
			opt = struct(optcell{:});
		end
		function [opt,optcell] = getOpts(optvar)
			if isstruct(optvar)
				optvar = opt2cell(optvar);
			end
			if numel(optvar) > 0 && ~ischar(optvar{1})
				error('Malformed options variable');
			end
			[~,defcell] = Opts.getOptDefaults;
			opt = ParseArgs(optvar,defcell{:});
			optcell = opt2cell(opt);
		end
	end
end
