% For old plotting scripts, see scratchpad/archived/plotting-scripts/*

% Script to plot data from 20150506_0500_explore_nSig.mat
% See also create_20150505_explore_nSig.m


function hF = plot_20150505_explore_nSig(varargin)
opt				= ParseArgs(varargin, ...
					'yVarName'		, 'acc'		  ...
					);

hF				= zeros(1,0);
stem			= '20150506_0500_explore_nSig';

load(['../data_store/' stem '.mat']);


% Capsule 1 multiplots

vertVar			= {								  ...
					'nDataPerRun'	, {48 96}	  ...
				  };
fixedPairs		= {								  ...
					'nRun'			, 10		, ...
					'WSum'			, 0.2		  ...
				  };
hF				= plot_quads_nTBlock_nSig(hF,cCapsule{1},opt.yVarName,vertVar,fixedPairs);

vertVar			= {								  ...
					'nRun'			, {5 10}	  ...
				  };
fixedPairs		= {								  ...
					'nDataPerRun'	, 96		, ...
					'WSum'			, 0.2		  ...
				  };
hF				= plot_quads_nTBlock_nSig(hF,cCapsule{1},opt.yVarName,vertVar,fixedPairs);

vertVar			= {								  ...
					'WSum'			, {0.1 0.2}	  ...
				  };
fixedPairs		= {								  ...
					'nDataPerRun'	, 96		, ...
					'nRun'			, 10		  ...
				  };
hF				= plot_quads_nTBlock_nSig(hF,cCapsule{1},opt.yVarName,vertVar,fixedPairs);


figfilepath		= sprintf('scratchpad/figfiles/%s-%s-%s.fig',stem, ...
					opt.yVarName,FormatTime(nowms,'mmdd'));
savefig(hF(end:-1:1),figfilepath);
fprintf('Plots saved to %s\n',figfilepath);

end

function hF = plot_quads_nTBlock_nSig(hF,capsule,yVarName,vertVar,fixedPairs)
	p			= Pipeline;
	ha			= p.renderMultiLinePlot(capsule,'nTBlock'		, ...
					'yVarName'				, yVarName			, ...
					'lineVarName'			, 'nSig'			, ...
					'lineVarValues'			, {10 30 60 100}	, ...
					'horizVarName'			, 'CRecur'			, ...
					'horizVarValues'		, {0 0.5}			, ...
					'vertVarName'			, vertVar{1}		, ...
					'vertVarValues'			, vertVar{2}		, ...
					'fixedVarValuePairs'	, fixedPairs		  ...
					);
	hF(end+1)	= ha.hF;

	ha			= p.renderMultiLinePlot(capsule,'nSig'			, ...
					'yVarName'				, yVarName			, ...
					'lineVarName'			, 'nTBlock'			, ...
					'lineVarValues'			, {1 3 8}			, ...
					'horizVarName'			, 'CRecur'			, ...
					'horizVarValues'		, {0 0.5}			, ...
					'vertVarName'			, vertVar{1}		, ...
					'vertVarValues'			, vertVar{2}		, ...
					'fixedVarValuePairs'	, fixedPairs		  ...
					);
	hF(end+1)	= ha.hF;
end
